### ISSUE TITLE
Automatic Instrumentation doesn't seem to work

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-python#109]
**Versions**

current

**Steps to reproduce**

1. run the flask app, see no automatic instrumentation for flask.

**Additional context**

The flask app should be automatically instrumented with the `opentelemetry-instrument` command line argument, but only manual instrumentation is being picked up. Smoke tests for the flask app should also be updated to include tests for auto-instr spans.

**Comment by emilyashley** [comment]
I was trying to get to the bottom of this version conflict when working on the docs. i.e. `double-check there are no dependency conflicts with installing latest release` For what it's worth, this may be a good sandbox to test it out in with the alpha release:

https://github.com/honeycombio/honeycomb-opentelemetry-python/issues/79#issuecomment-1462987451

**Comment by JamieDanielson** [comment]
Tests have now been added for auto-instrumented spans, and poetry locks have been removed from example apps to ensure smoke tests are using examples built with fresh installs. These changes help us ensure this is working as expected, and this now works in our Example Greeting Service after removing a flask debug variable.

If anyone runs into version conflicts after the beta release is published and docs are updated with details on how to use the beta package, we are open to new issues describing how to get into that state so we can help document as needed.

Closing this issue as we seem to have worked out the kinks, and will update docs if any new information comes in that is worth documenting for troubleshooting.
