### ISSUE TITLE
Python not catching root span_id's originating from a JavaScript front-end, so distributed tracing doesn't quite work

### ISSUE THREAD

**Issue by ericnograles** [honeycombio/honeycomb-opentelemetry-python#139]
### Python

```
opentelemetry-api==1.17.0
opentelemetry-exporter-otlp==1.17.0
opentelemetry-exporter-otlp-proto-grpc==1.17.0
opentelemetry-exporter-otlp-proto-http==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-aiohttp-client==0.38b0
opentelemetry-instrumentation-aws-lambda==0.38b0
opentelemetry-instrumentation-dbapi==0.38b0
opentelemetry-instrumentation-flask==0.38b0
opentelemetry-instrumentation-grpc==0.38b0
opentelemetry-instrumentation-jinja2==0.38b0
opentelemetry-instrumentation-logging==0.38b0
opentelemetry-instrumentation-requests==0.38b0
opentelemetry-instrumentation-sqlalchemy==0.38b0
opentelemetry-instrumentation-sqlite3==0.38b0
opentelemetry-instrumentation-urllib==0.38b0
opentelemetry-instrumentation-urllib3==0.38b0
opentelemetry-instrumentation-wsgi==0.38b0
opentelemetry-propagator-aws-xray==1.0.1
opentelemetry-proto==1.17.0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
```

### JavaScript

```
    "@opentelemetry/api": "^1.4.1",
    "@opentelemetry/context-zone": "^1.13.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.39.0",
    "@opentelemetry/instrumentation": "^0.39.0",
    "@opentelemetry/instrumentation-fetch": "^0.39.0",
    "@opentelemetry/instrumentation-xml-http-request": "^0.39.0",
    "@opentelemetry/propagator-b3": "^1.13.0",
    "@opentelemetry/sdk-trace-web": "^1.13.0",
```

## Steps to reproduce

1. Begin a trace on the front-end
2. Observe Honeycomb collection
3. Observe the corresponding backend trace to not capture the front-end's span_id as its parent_span_id

## Additional context

Hi there,

Me again! 😇

I wasn't sure if I needed to log this on your JavaScript GH repo or here, but I figured I'd start here since @JamieDanielson has been so incredibly helpful.

Good news: All my OTel SDK sending to Honeycomb doo-hickeys are working. Yay!

Bad news: I'm having trouble with distributed tracing. I do see traces from our front-end land in Honeycomb, but their corresponding backend calls don't seem to grab the front-end's span_id as their parent_span_id, and I don't get full distributed tracing. I did read through [the troubleshooting docs](https://docs.honeycomb.io/getting-data-in/tracing/troubleshooting/#verify-that-traceparent_id-tracetrace_id-and-tracespan_id-are-set-properly) but couldn't spot anything obvious.

I'm assuming it's a Python issue since the front-end is sending span_id's as expected. Was there something I missed in the Python docs that enabled `opentelemetry-instrument` to properly infer parent span id's? Another guess I have is that the support for that isn't out of the box and I may have to write middleware in Flask to attach a parent_span_id? (I recall having to do something similar in DataDog in the past)

Thanks again for any information!

### Screenshots

**Front-end Span**

![image](https://github.com/honeycombio/honeycomb-opentelemetry-python/assets/6023705/72f19c36-915a-4bd4-8ff5-d5b59a248903)

**Backend Span**

![image](https://github.com/honeycombio/honeycomb-opentelemetry-python/assets/6023705/7497c8db-489d-478b-ba8a-1562be66a090)

### Other Context

Here's how I scaffold things on the JavaScript side. On the Python side, I use `FLASK_DEBUG=false opentelemetry-instrument python application.py` to launch the Flask API.

```
// tracing.js
import * as otelCore from "@opentelemetry/core"
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { WebTracerProvider, BatchSpanProcessor } from '@opentelemetry/sdk-trace-web';
import { ZoneContextManager } from '@opentelemetry/context-zone';
import { Resource }  from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { XMLHttpRequestInstrumentation } from '@opentelemetry/instrumentation-xml-http-request';
import { FetchInstrumentation } from '@opentelemetry/instrumentation-fetch';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { B3Propagator, B3InjectEncoding } from "@opentelemetry/propagator-b3";

const exporter = new OTLPTraceExporter({
  url: "https://api.honeycomb.io/v1/traces",
  headers: {
    "x-honeycomb-team": import.meta.env.VITE_HONEYCOMB_API_KEY
  }
});
const provider = new WebTracerProvider({
  resource: new Resource({
    // TODO: Make this configurable
    [SemanticResourceAttributes.SERVICE_NAME]: import.meta.env.VITE_OTEL_SERVICE_NAME
  }),
});
provider.addSpanProcessor(new BatchSpanProcessor(exporter));

// setup Propagator
const propagator = new otelCore.CompositePropagator({
  propagators: [
    new B3Propagator(),
    new B3Propagator({ injectEncoding: B3InjectEncoding.MULTI_HEADER })
  ]
})
provider.register({
  contextManager: new ZoneContextManager(),
  propagator
});

registerInstrumentations({
  instrumentations: [
    new XMLHttpRequestInstrumentation({
      propagateTraceHeaderCorsUrls: [
        /http:\/\/127.0.0.1:5000\.*/,
        /diffit\.me/i,
        /vercel\.app/i
      ]
    }),
    new FetchInstrumentation({
      propagateTraceHeaderCorsUrls: [
        /http:\/\/127.0.0.1:5000\.*/,
        /diffit\.me/i,
        /vercel\.app/i
      ]
    }),
  ],
});

```

**Comment by robbkidd** [comment]
Hi there, @ericnograles!

My first suspect is propagation header format.

I notice that JS frontend is configured in code to propagate trace information with B3 headers.


```js
// setup Propagator
const propagator = new otelCore.CompositePropagator({
  propagators: [
    new B3Propagator(),
    new B3Propagator({ injectEncoding: B3InjectEncoding.MULTI_HEADER })
  ]
})
provider.register({
  contextManager: new ZoneContextManager(),
  propagator
});
```

 If your Python backend is not _also_ configured for B3 propagation—which is not the default; propagation format defaults to W3C an OTel SDK—then that would explain this behavior. Both services emit spans, but the backend starts a new trace for its spans because it ignores the B3 header on the incoming traffic from the frontend.

The options I see:

* Configure the Python backend to propagate tracing in-and-out in B3 format. Depending on how you are configuring OpenTelemetry in the backend, this could be as simple as setting [the OTEL_PROPAGATORS environment variable](https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_propagators) to "b3" .
* Configure the JS frontend to propagate with W3C format, unless you have some specific reasons for using B3 like communications with other components in which B3 is the recommended or only supported format. W3C is the default in an OTel SDK, so this option might be a matter of removing the `propagator` construction and its use in `provider.register()`.

**Comment by robbkidd** [comment]
As a side note, @ericnograles, thank you for providing such thorough information in your issues! They are like exemplars for how to give enough information for someone else to help! 💞

**Comment by robbkidd** [comment]
@ericnograles `parent_id` not set is still an indicator that propagation is not aligned between your frontend and backend.

Some things I can think to look at:

1. Can you see the headers on HTTP requests received by your backend? If the frontend is correctly configured to propagate W3C trace context, you should see `traceparent` headers on requests from your frontend.
2. Can you share your updated JS OTel config?
3. Can you share your Python backend's OTel config as well? And any `OTEL_*` environment variables you may have set there.
    - :warning: REDACT any secrets you find in the values for these variables before sharing.
