### ISSUE TITLE
When creating HoneycombOptions, do not append /v1/traces to traces_endpoint if it's already there

### ISSUE THREAD

**Issue by omervk** [honeycombio/honeycomb-opentelemetry-python#155]
Hey y'all 👋🏻 
Thanks for the great bootstrapping library :)

> **Is your feature request related to a problem? Please describe.**

I tried instantiating HoneycombOptions with `https://<collector url>/v1/traces` and got unhelpful error messages and no traces exported.

> **Describe the solution you'd like**

If I instantiate HoneycombOptions with an `endpoint` that ends with `/v1/traces` and `exporter_protocol=EXPORTER_PROTOCOL_HTTP_PROTO`, do not append that suffix again.

> **Describe alternatives you've considered**

An alternative is to warn users that they're providing an invalid value to the field.

**Comment by MikeGoldsmith** [comment]
Thanks for raising @omervk - I've got a fix incoming 👍🏻
