### ISSUE TITLE
Upgrade supported version of OpenTelemetry SDK

### ISSUE THREAD

**Issue by estraph** [honeycombio/honeycomb-opentelemetry-python#167]
This project has a dependency constraint on the opentelemetry SDK version 1.20 aka 0.41b0

https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/5f932a6ae8823b636f07fc4652725a91d78b0427/pyproject.toml#L11-L14

At the time of writing there have been [two releases](https://github.com/open-telemetry/opentelemetry-python/releases) of the opentelemetry SDK since:
* https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.21.0
* https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.22.0

Can you please release an updated version of this library with support for the latest version of opentelemetry?

**Comment by estraph** [comment]
Hi Honeycomb team 🌈  any news on this? This constraint makes it impossible for us to use newer versions of the python OTel library. Considering Honeycomb's dedication to opentelemetry I would expect more interest in staying up to date. Let me know if there's anything I can do to help.

**Comment by estraph** [comment]
Thank you @JamieDanielson!

**Comment by JamieDanielson** [comment]
The new version should be available tomorrow  @estraph , will ping back here once it's released!

**Comment by JamieDanielson** [comment]
Hey @estraph [new version v0.2.4b0 is out](https://github.com/honeycombio/honeycomb-opentelemetry-python/releases/tag/v0.2.4b0)! Thanks for the poke.

**Comment by estraph** [comment]
Amazing, thank you 🚀
