### ISSUE TITLE
Package is missing `license` metadata - add key and trove classifiers?

### ISSUE THREAD

**Issue by Zac-HD** [honeycombio/honeycomb-opentelemetry-python#174]
Hi there!  I noticed that while you include a [`LICENSE` file](https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/main/LICENSE) in this repo, the package published on PyPI doesn't declare any license metadata - and that would be nice to have for downstream audits etc.

[Fortunately it's easy to add](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license), ideally via [trove classifiers](https://pypi.org/classifiers/) and perhaps also via the `license=` string.  You might also want to add trove classifiers such as `Development Status :: 4 - Beta`, and perhaps other metadata [like `requires-python = ">= 3.8"`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires).  Let me know if I can help 🙂

**Comment by MikeGoldsmith** [comment]
Hey @Zac-HD - thanks for raising the issue. We'll look into getting this updated 👍
