### ISSUE TITLE
Support latest OpenTelemetry SDK

### ISSUE THREAD

**Issue by vsakkasld** [honeycombio/honeycomb-opentelemetry-python#195]
This project has a dependency constraint on the opentelemetry SDK 0.43b0 which causes issues when trying to use newer versions, as can be seen here:

```
ERROR: Unable to find a resolution for opentelemetry-instrumentation
because of the following conflicts:
  opentelemetry-instrumentation<0.44,>=0.43b0 (from honeycomb-opentelemetry@0.4.2b0)
  opentelemetry-instrumentation==0.45b0 (from opentelemetry-instrumentation-aws-lambda@0.45b0)
```

Is it possible to release an update with more relaxed constraints?

**Comment by MikeGoldsmith** [comment]
Hi @vsakkasld - thanks for opening the issue.

The OTel API, SDK and OTLP exporter packages are all locked to a minimum of v1.22.0 and allows higher versions.

The opentelemtry-instrumentation package version is set as `~0.43b0`. It uses the [tilde version constraint](https://python-poetry.org/docs/dependency-specification/#tilde-requirements) which is more restrictive by only allowing updates within the same minor version.

I'll look at updating the requirements to be less restrictive.

**Comment by vsakkasld** [comment]
Thank you @MikeGoldsmith for the quick response!

I'll give the new release once it's ready
