### ISSUE TITLE
Improve docs around auto and manual SDK configuration options

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-python#57]
Ensure docs describe both auto and manual SDK configuration using the distro.

For example:
- Auto instrumentation with `opentelemetry-instrument`
- Manual configuration with `configure_opentelemetry`

Note: our hello-world-flask example only show auto instrumentation.

**Comment by emilyashley** [comment]
note: clarify this --> https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/main/examples/hello-world/app.py#L31
