### ISSUE TITLE
should opentelemetry-instrument read code config?

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-python#67]
I run with opentelemetry-instrument, it doesn’t pick up [my code configuration in this app](https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/main/examples/hello-world/app.py).

`poetry run opentelemetry-instrument python3 app.py` results in `unknown_service:python` and debug is not true.

`poetry run python3 app.py` correctly picks up those env vars 🤔 

I guess the question is… should it? Or does using `opentelemetry-instrument` mean you can only use env vars and not config in code with `configure_opentelemetry`?

**Comment by emilyashley** [comment]
@JamieDanielson I'm curious if you think this documentation makes it clear that we expect one or the other? https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/main/src/honeycomb/opentelemetry/distro.py#L3

If so, we'll make sure to put this in the main documentation and we can close this issue?

**Comment by MikeGoldsmith** [comment]
Yep, that's right - both opentelemetry-instrument and configure_opentelemetry trigger the distro hook to configure the OTel SDK. If both are called, it will configure the SDK twice, which can lead to unexpected setups.

If you want a zero-code solution that's only driven by env vars you would use `opentemetry-instrument`.
if you want to configure via code (and optionally mix with env vars), you would use `configure_opentelemetry`.

**Comment by emilyashley** [comment]
Great! I'll make sure it's extra clear which example app uses which way! This looks good to close to me ✨
