### ISSUE TITLE
add way to clear env vars before running tests

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-python#69]
**Is your feature request related to a problem? Please describe.**

Unexpected behavior and failing tests when running tests with some environment variables set locally.

**Describe the solution you'd like**

Find a way to clear environment variables before test runs, similar to how we used the [setup-jest file](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/test/setup-jest.ts) for the node distro.

**Describe alternatives you've considered**

currently just manually unsetting environment variables

**Additional context**

Something like [monkeypatching environment variables](https://docs.pytest.org/en/stable/how-to/monkeypatch.html#monkeypatching-environment-variables) seems to work but it involves a lot of extra copy/paste:

```python
import pytest

@pytest.fixture
def mock_env_missing(monkeypatch):
    monkeypatch.delenv("OTEL_SERVICE_NAME", raising=False)

def test_defaults(mock_env_missing):

...
def test_can_set_service_name_with_envvar(monkeypatch):
```

**Comment by to-json** [comment]
On second examination, I had forgotten how impossible using `$` expansions in `make` was; however, setting the shell to `bash` in the `Makefile` appears to make the regex based `unset` work. PR above, since I already dug around and tried it.
