### ISSUE TITLE
[user] docs.honeycomb

### ISSUE THREAD

**Issue by emilyashley** [honeycombio/honeycomb-opentelemetry-python#79]
- [x] Requirements
- [x] Examples
- [x] ~Initialize~
- [x] Automatic Instrumentation
     - [ ] Install Packages
          - [ ] double-check there are no dependency conflicts with installing latest release 
     - [x] Configure and Run
     - [x] ~GRPC vs HTTP~
     - [x] Advanced Configuration
- [x] Manual Instrumentation
     - [x] Creating Spans
     - [x] Adding Attributes to Spans
     - [x] Propagating Baggage
- [x] Sampling
     - [x] Deterministic Sampler, Sample Rate Attribute. 
- [x] Distributed Trace Propagation
- [ ] Troubleshooting 
     - [ ] (ensure existing sections are still relevant)
     - [x] Exporting to the console

https://github.com/honeycombio/docs/pull/1684

**Comment by emilyashley** [comment]
To double-check there are no dependency conflicts with latest alpha release, I've been using this Flask example https://github.com/pallets/flask/tree/main/examples/tutorial

Basically, with that example cloned down you'll need to do these steps to make sure it works as expected:
```
pip install -e .
pip install --pre honeycomb-opentelemetry
pip install opentelemetry-instrumentation-flask 
# ^this is where there was currently a conflict that needed resolution
```

To run the app and see spans locally:
```
$ flask --app flaskr init-db 
$ DEBUG=TRUE opentelemetry-instrument flask --app flaskr run
```

**Comment by MikeGoldsmith** [comment]
PR merged
