### ISSUE TITLE
Django docs

### ISSUE THREAD

**Issue by cartermp** [honeycombio/honeycomb-opentelemetry-python#95]
Django's a thing. I think in our docs we should at least acknowledge it and mention or link to the appropriate instrumentation to install for Django apps. Probably not worth a whole-hog sample and docs section though.

**Comment by mterhar** [comment]
@tdarwin whatever we find out should probably end up here. Some users are struggling with this and our first attempt isn't working either.

**Comment by JamieDanielson** [comment]
I added [these docs](https://docs.honeycomb.io/getting-data-in/opentelemetry/python-distro/#django-instrumentation) at some point which should help a bit, copy-pasting here for quick reference:

### Django Instrumentation

If the application uses Django, instrumentation requires the `DJANGO_SETTINGS_MODULE` and the `--noreload` flag.

First set the environment variable for `DJANGO_SETTINGS_MODULE` based on the name of your settings file.

```shell
export DJANGO_SETTINGS_MODULE=myapp.settings
```

Then run the application with the `--noreload` flag to avoid Django running `main` twice.

For example, the command to run the application may look like this:

```shell
opentelemetry-instrument python manage.py runserver --noreload
```
